### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by rubdos**
`serde_derive::Serialize` imports start to conflict when a user of this crate has `serde` with the derive feature enabled. Just use `derive` ourselves, that doesn't do harm.

Second, I had logbook entries without entity_id, so I made that optional.

Cheers, thanks for the crate!

I might come back and throw a websocket API at it some day, but https://github.com/seanmonstar/reqwest/issues/864 seems to be in the way for that :-)

---

FWIW, I just built this with it: https://gitlab.com/rubdos/hasli/

I have some pending code that infers whether someone is in the shower, and I intent to make it a big bigger than that.

### CODE REVIEW

**Comment by StefanBossbaly** [comment]
LGTM and thanks for the fixes. I wrote this library for a project that I am currently working on so there may be some API churn. Feel free file issues or submit fixes in the future.

**Comment by rubdos** [comment]
> I wrote this library for a project that I am currently working on so there may be some API churn.

I live by API churn! I might be rewriting my project as a real Home Assistant integration, because I'd need to expose service calls too, so I don't know whether I'll keep using your work here. If I do, I'll certainly file PRs and issues :-)

**Comment by StefanBossbaly** [comment]
Looks like the tests need to be updated as well. The Github action is reporting:

```
error[E0432]: unresolved import `serde_derive`
 --> tests/state_enum.rs:5:5
  |
5 | use serde_derive::Deserialize;
  |     ^^^^^^^^^^^^ use of undeclared crate or module `serde_derive`

error: cannot determine resolution for the derive macro `Deserialize`
 --> tests/state_enum.rs:7:10
  |
7 | #[derive(Deserialize, Debug)]
  |          ^^^^^^^^^^^
  |
  = note: import resolution is stuck, try simplifying macro imports

error: cannot find attribute `serde` in this scope
 --> tests/state_enum.rs:9:7
  |
9 |     #[serde(deserialize_with = "deserialize_state_enum")]
  |       ^^^^^
  |
  = note: `serde` is in scope, but it is a crate, not an attribute

error: cannot determine resolution for the derive macro `Deserialize`
  --> tests/state_enum.rs:13:10
   |
13 | #[derive(Deserialize, Debug)]
   |          ^^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: cannot find attribute `serde` in this scope
  --> tests/state_enum.rs:15:7
   |
15 |     #[serde(deserialize_with = "deserialize_optional_state_enum")]
   |       ^^^^^
   |
   = note: `serde` is in scope, but it is a crate, not an attribute

warning: unused imports: `deserialize_optional_state_enum`, `deserialize_state_enum`
 --> tests/state_enum.rs:2:19

...
```

**Comment by rubdos** [comment]
Fixed the tests! :-)

**Comment by rubdos** [comment]
e92adf5 removes some unnecessary allocations that I saw happening in the tests. Not very relevant, but thought I'd fix that while I was at it.

**Pull request merged**
